name: Trigger External Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tekton Pipeline
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          curl -X POST -H "Authorization: Bearer ${{ secrets.TEKTON_API_TOKEN }}" "${{ secrets.TEKTON_PIPELINE_URL }}?branch=$branch_name"

